embed:
text_model: "sentence-transformers/all-MiniLM-L6-v2" # 可換 bge/e5
image_model: "openai/clip-vit-base-patch32" # 可換 siglip
dim_text: 384
dim_image: 512


ocr:
enabled: true
lang: "eng" # 可改為 "chi_sim+eng" 視需求


retrieval:
top_k_text: 5
top_k_image: 4
fuse: "rrf" # rrf / weighted


storage:
vector_dir: "data/embeddings"
table_dir: "data/tables"


ui:
show_traces: true